# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Codemagic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Call Codemagic API
        run: >
        curl -H "Content-Type : application/json" -H "x-auth-token : 1gzKlwuOPQP5g2pEETQXQd_HZhX9Xg404zxtmGJ-qNY" \n
        --data '{"appId" : "60492f97478667ea16edeaf5","workflowId" : "60492f97478667ea16edeaf4","branch" : "main"}' \n
        https://api.codemagic.io/builds
