--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Call Codemagic API"
        run: "curl -H \"Content-Type application/json\" -H \"x-auth-token 1gzKlwuOPQP5g2pEETQXQd_HZhX9Xg404zxtmGJ-qNY\" --data '{\"appId\" \"60492f97478667ea16edeaf5\",\"workflowId\" \"60492f97478667ea16edeaf4\",\"branch\" \"main\"}' https://api.codemagic.io/builds"
name: Codemagic
true: 
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
